[package]
name = "iron_planet"
version = "0.0.0"
edition = "2021"


[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
serde_repr = "0.1.7"
slab = "0.4"
once_cell = "1.8.0"
ureq = "2.3.0"